// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC75CtgWxRQQhyVzmAV3lBCqWrmLsZ-7e0',
    appId: '1:39709551679:web:8039fbbb30ce1c87bb9c8a',
    messagingSenderId: '39709551679',
    projectId: 'gnut06-bh',
    authDomain: 'gnut06-bh.firebaseapp.com',
    storageBucket: 'gnut06-bh.firebasestorage.app',
    measurementId: 'G-YGZ2HRR20J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBIPS2mUmvuX1ycfbEmkXPW30ea_V9SaM',
    appId: '1:39709551679:android:d51dab689c57759ebb9c8a',
    messagingSenderId: '39709551679',
    projectId: 'gnut06-bh',
    storageBucket: 'gnut06-bh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLTer3Xcf4VYeYjdUSQuUq8u2rFjiOdI',
    appId: '1:39709551679:ios:0c53dfefede73650bb9c8a',
    messagingSenderId: '39709551679',
    projectId: 'gnut06-bh',
    storageBucket: 'gnut06-bh.firebasestorage.app',
    iosBundleId: 'com.example.gnut06MobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLTer3Xcf4VYeYjdUSQuUq8u2rFjiOdI',
    appId: '1:39709551679:ios:0c53dfefede73650bb9c8a',
    messagingSenderId: '39709551679',
    projectId: 'gnut06-bh',
    storageBucket: 'gnut06-bh.firebasestorage.app',
    iosBundleId: 'com.example.gnut06MobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC75CtgWxRQQhyVzmAV3lBCqWrmLsZ-7e0',
    appId: '1:39709551679:web:a11049233db17da8bb9c8a',
    messagingSenderId: '39709551679',
    projectId: 'gnut06-bh',
    authDomain: 'gnut06-bh.firebaseapp.com',
    storageBucket: 'gnut06-bh.firebasestorage.app',
    measurementId: 'G-LCKSZZJ8ER',
  );
}
